FROM node:20-bullseye

WORKDIR /usr/app/mybeans-backend

COPY package*.json ./
RUN npm install

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY prisma ./prisma
COPY src ./src
COPY upload ./upload
COPY docker/local/.env ./

RUN npx prisma generate

EXPOSE ${SERVER_PORT}