export enum RoleEnum {
  USER = 'USER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
}

export enum SignSnsErrorEnum {
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_UNVERIFIED = 'EMAIL_UNVERIFIED', // (구글/카카오에 주로 사용)
  NAME_REQUIRED = 'NAME_REQUIRED',
  DOMAIN_MISMATCH = 'DOMAIN_MISMATCH', // (구글 hd 제한에 주로 사용)
  PROVIDER_USERINFO_FAILED = 'PROVIDER_USERINFO_FAILED',
  STATE_INVALID = 'STATE_INVALID',
  SCOPE_INSUFFICIENT = 'SCOPE_INSUFFICIENT',
  TOKEN_EXCHANGE_FAILED = 'TOKEN_EXCHANGE_FAILED', // (authenticate~userProfile 사이 단계)
  CONFIG_MISCONFIGURED = 'CONFIG_MISCONFIGURED', // (env 누락)
}
