export enum CProductStatusEnum {
  ON = 'A', // 판매중
  OFF = 'B', // 판매중단
}

export enum ValidationIssueEnum {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_OFF = 'PRODUCT_OFF',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  SALE_WINDOW_CLOSED = 'SALE_WINDOW_CLOSED',
  QTY_OUT_OF_RANGE = 'QTY_OUT_OF_RANGE',
  DUPLICATE_OPTION_VALUE = 'DUPLICATE_OPTION_VALUE',
  REQUIRED_OPTION_MISSING = 'REQUIRED_OPTION_MISSING',
  REQUIRED_OPTION_TOO_MANY = 'REQUIRED_OPTION_TOO_MANY',
  OPTION_VALUE_NOT_BELONGS = 'OPTION_VALUE_NOT_BELONGS',
}
